from pathlib import Path
p=Path('/tmp/a2-pwa/www/app.html')
s=p.read_text()
marker='</style>'
css='''\n<style id="a2-live-notifications">\n.a2-notify-bell{position:fixed;right:18px;top:16px;z-index:9998;border:1px solid rgba(255,255,255,.15);background:#0c2d25;color:#fff;border-radius:14px;width:46px;height:46px;font-size:21px;box-shadow:0 10px 30px #0004}.a2-notify-badge{position:absolute;right:-4px;top:-5px;min-width:20px;height:20px;padding:0 5px;border-radius:20px;background:#ef4444;color:#fff;font:700 11px/20px system-ui}.a2-notify-panel{position:fixed;right:16px;top:70px;width:min(390px,calc(100vw - 24px));max-height:70vh;overflow:auto;z-index:9999;background:#09251f;color:#fff;border:1px solid rgba(255,255,255,.13);border-radius:20px;box-shadow:0 22px 60px #0008;padding:14px}.a2-notify-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.a2-notify-item{padding:11px 12px;margin:8px 0;border-radius:13px;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.08)}.a2-notify-item b{display:block;margin-bottom:3px}.a2-notify-time{opacity:.65;font-size:11px}.a2-notify-empty{opacity:.7;text-align:center;padding:28px 10px}@media(max-width:620px){.a2-notify-bell{top:10px;right:10px}.a2-notify-panel{right:8px;top:64px;width:calc(100vw - 16px)}}\n</style>\n'''
if 'id="a2-live-notifications"' not in s:s=s.replace(marker,marker+css,1)
js=r'''\n<script id="a2-live-notifications-runtime">\n(()=>{\n const seenKey='a2_notification_seen_v1'; let feed=[],open=false;\n const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));\n const ts=x=>{const v=x?.updatedAt||x?.createdAt||x?.timestamp||x?.date||x?.paymentDate||x?.expenseDate;try{return v?.toDate?v.toDate():new Date(v)}catch(e){return new Date(0)}};\n const id=(kind,x)=>kind+':'+(x?.id||x?.docId||[x?.memberId,x?.amount,x?.date,x?.createdAt?.seconds].join(':'));\n function build(){const d=window.state?.data||{};let a=[];(d.payments||[]).forEach(x=>a.push({id:id('payment',x),t:ts(x),title:'Payment Received',body:`${x.memberName||x.name||'Member'} · AED ${Number(x.amount??x.paidAmount??0).toFixed(2)} · ${String(x.paymentMethod||'').toUpperCase()==='ACCOUNT_TRANSFER'?'Account Transfer':String(x.paymentMethod||'').toUpperCase()==='CASH'?'Cash':'Method not recorded'}`}));(d.expenses||[]).forEach(x=>a.push({id:id('expense',x),t:ts(x),title:'Expense Added',body:`${x.category||x.description||'Expense'} · AED ${Number(x.amount||0).toFixed(2)}`}));(d.mealSkips||[]).forEach(x=>a.push({id:id('skip',x),t:ts(x),title:'Meal Skipped',body:`${x.memberName||x.name||'Member'} · ${x.meal||x.mealType||'Meal'}`}));feed=a.sort((a,b)=>b.t-a.t).slice(0,40);render();}\n function seen(){try{return new Set(JSON.parse(localStorage.getItem(seenKey)||'[]'))}catch(e){return new Set()}}\n function unread(){const q=seen();return feed.filter(x=>!q.has(x.id)).length}\n function markAll(){localStorage.setItem(seenKey,JSON.stringify(feed.map(x=>x.id)));render()}\n function render(){let b=document.getElementById('a2NotifyBell');if(!b){b=document.createElement('button');b.id='a2NotifyBell';b.className='a2-notify-bell';b.innerHTML='🔔<span id="a2NotifyBadge" class="a2-notify-badge"></span>';b.onclick=()=>{open=!open;if(open)markAll();render()};document.body.appendChild(b)}const n=unread(),badge=document.getElementById('a2NotifyBadge');if(badge){badge.textContent=n>99?'99+':n;badge.style.display=n?'block':'none'}let p=document.getElementById('a2NotifyPanel');if(!open){p?.remove();return}if(!p){p=document.createElement('div');p.id='a2NotifyPanel';p.className='a2-notify-panel';document.body.appendChild(p)}p.innerHTML=`<div class="a2-notify-head"><b>🔔 Live Notifications</b><button onclick="document.getElementById('a2NotifyPanel')?.remove()" style="background:none;border:0;color:white;font-size:20px">×</button></div>`+(feed.length?feed.map(x=>`<div class="a2-notify-item"><b>${esc(x.title)}</b><div>${esc(x.body)}</div><div class="a2-notify-time">${isNaN(x.t)?'':x.t.toLocaleString()}</div></div>`).join(''):'<div class="a2-notify-empty">No notifications yet</div>')}\n const obs=new MutationObserver(()=>{clearTimeout(window.__a2NotifyTimer);window.__a2NotifyTimer=setTimeout(build,250)});obs.observe(document.documentElement,{subtree:true,childList:true});setInterval(build,5000);setTimeout(build,1200);\n})();\n</script>\n'''
if 'a2-live-notifications-runtime' not in s:s=s.replace('</body>',js+'</body>',1)
p.write_text(s)
print('Added live notification bell, unread badge and realtime activity panel')
