from pathlib import Path
import sys

def patch(app: Path):
    s = app.read_text()

    def cut(text, a, b, repl):
        i = text.find(a)
        j = text.find(b, i)
        if i < 0 or j < 0:
            raise SystemExit(f'{app}: marker missing: {a} / {b}')
        return text[:i] + repl.rstrip() + "\n" + text[j:]

    helpers = r'''function planValue(v){const n=Number(String(v??'').replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:0}
function paidValue(x){const n=Number(x?.paidAmount??x?.amount??0);return Number.isFinite(n)?n:0}
function money(n){return Number(n||0).toFixed(2)}
function monthKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0');return `${y}-${m}`}
function currentBillingMonth(){return monthKey(new Date())}
function timestampMonth(v){try{const d=v?.toDate?.();return d?monthKey(d):''}catch{return ''}}
function paymentMonth(p){return String(p?.billingMonth||timestampMonth(p?.createdAt)||timestampMonth(p?.updatedAt)||currentBillingMonth())}
function recordMonth(x){return String(x?.billingMonth||timestampMonth(x?.createdAt)||timestampMonth(x?.updatedAt)||currentBillingMonth())}
function memberKey(m){return String(m?.uid||m?.id||'')}
function linkedMember(uid){return state.data.members.find(m=>memberKey(m)===String(uid||''))}
function memberPaid(m,month=currentBillingMonth(),excludeId=''){const k=memberKey(m);return state.data.payments.reduce((sum,p)=>sum+((p.id!==excludeId&&String(p.uid||'')===k&&paymentMonth(p)===month)?paidValue(p):0),0)}
function paymentStatus(plan,paid){const due=Math.max(0,plan-paid);return paid<=0?'DUE':due>0?'PARTIAL':'PAID'}
function memberSummary(m,month=currentBillingMonth()){const plan=planValue(m?.planAmount||m?.plan),paid=memberPaid(m,month),due=Math.max(0,plan-paid);return{plan,paid,due,status:paymentStatus(plan,paid),month}}
function currentMonthExpenses(){const month=currentBillingMonth();return state.data.expenses.filter(x=>recordMonth(x)===month)}
'''
    if 'function currentBillingMonth()' not in s:
        marker = 'function dashboard(){'
        if marker not in s:
            raise SystemExit(f'{app}: dashboard marker missing')
        # Remove the older helper block if it exists, then install one canonical helper block.
        if 'function planValue(v)' in s:
            a=s.find('function planValue(v)')
            b=s.find('function dashboard(){',a)
            if a>=0 and b>a:
                s=s[:a]+helpers+'\n'+s[b:]
        else:
            s=s.replace(marker,helpers+'\n'+marker,1)
    if '.tag.partial{' not in s:
        s=s.replace('</style>','.tag.partial{background:#f6cb67;color:#201600}\n.tag.paid{background:#45f0a6;color:#032016}\n</style>',1)

    dashboard = r'''function dashboard(){const month=currentBillingMonth();if(state.profile.role==='member'){const member=linkedMember(auth.currentUser.uid);if(!member)return`<div class=card style="margin-top:14px"><h3>Member account not linked</h3><p class=muted>Ask Admin to link this login to your member record.</p></div>`;const q=memberSummary(member,month),expenses=currentMonthExpenses(),totalExpense=expenses.reduce((a,x)=>a+Number(x.amount||0),0),cats={};expenses.forEach(x=>{const k=x.category||'General';cats[k]=(cats[k]||0)+Number(x.amount||0)});const entries=Object.entries(cats).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>x[1])),progress=q.plan?Math.min(100,(q.paid/q.plan)*100):0;return`<div class=note style="margin-top:12px">Billing month: <b>${month}</b> · Status: <b>${q.status}</b></div><div class=grid>${metric('Total Receivable','AED '+money(q.plan))}${metric('You Paid','AED '+money(q.paid))}${metric('Balance Due','AED '+money(q.due))}${metric('Total Mess Expense','AED '+money(totalExpense))}</div><div class=card style="margin-top:12px"><div class=top><div><h3 style="margin:0">Payment Progress</h3><div class=small>Read only</div></div><b>${progress.toFixed(0)}%</b></div><div style="height:12px;background:#ffffff10;border-radius:99px;overflow:hidden;margin-top:12px"><div style="height:100%;width:${progress}%;background:linear-gradient(90deg,#45f0a6,#f6cb67);border-radius:99px"></div></div></div><div class=card style="margin-top:12px"><div class=top><div><h3 style="margin:0">Expense Chart</h3><div class=small>${month} · view only</div></div><b>AED ${money(totalExpense)}</b></div><div class=list style="margin-top:14px">${entries.length?entries.map(([name,val])=>`<div><div class=top style="font-size:13px"><span>${esc(name)}</span><b>AED ${money(val)}</b></div><div style="height:10px;background:#ffffff10;border-radius:99px;overflow:hidden;margin-top:6px"><div style="height:100%;width:${Math.max(4,(val/max)*100)}%;background:linear-gradient(90deg,#45f0a6,#f6cb67);border-radius:99px"></div></div></div>`).join(''):'<p class=muted>No expenses recorded this month.</p>'}</div></div>`}const summaries=state.data.members.map(m=>memberSummary(m,month)),paid=summaries.reduce((a,q)=>a+q.paid,0),due=summaries.reduce((a,q)=>a+q.due,0),exp=currentMonthExpenses().reduce((a,x)=>a+Number(x.amount||0),0),paidCount=summaries.filter(q=>q.status==='PAID').length,partialCount=summaries.filter(q=>q.status==='PARTIAL').length,dueCount=summaries.filter(q=>q.status==='DUE').length;return`<div class=note style="margin-top:12px">Billing month: <b>${month}</b> · Paid ${paidCount} · Partial ${partialCount} · Due ${dueCount}</div><div class=grid>${metric('Members',state.data.members.length)}${metric('Collected','AED '+money(paid))}${metric('Outstanding','AED '+money(due))}${metric('Expenses','AED '+money(exp))}</div>`}'''
    s = cut(s,'function dashboard(){','function users(){',dashboard)

    members = r'''function members(){const month=currentBillingMonth();return`<div class=top style="margin-top:14px"><div><p class=muted style="margin:0">Subscription members · ${month}</p><div class=small>Payment status is calculated from linked payment transactions.</div></div>${state.profile.role==='admin'?'<button class=btn onclick=memberForm()>+ Member Record</button>':''}</div><div class="card list">${state.data.members.map(x=>{const q=memberSummary(x,month);return`<div class=row><span><b>${esc(x.name)}</b><small class=muted> · Plan AED ${money(q.plan)}</small></span><span>Paid AED ${money(q.paid)}<br><small class=muted>Due AED ${money(q.due)}</small></span><span class="tag ${q.status==='DUE'?'due':q.status==='PARTIAL'?'partial':'paid'}">${q.status}</span><span>${state.profile.role==='admin'?`<div class=actions><button class=ghost onclick="paymentFormForMember('${memberKey(x)}')">Payment</button><button class=ghost onclick="memberFormById('${x.id}')">Edit</button><button class="ghost danger" onclick="delRecord('members','${x.id}','member')">Delete</button></div>`:''}</span></div>`}).join('')}</div>`}
window.memberForm=(x={})=>{const q=x.id?memberSummary(x):{plan:planValue(x.plan||'AED 200'),paid:0,due:planValue(x.plan||'AED 200'),status:'DUE'};modal(`<div class=top><h3>Member</h3><button class=ghost onclick=closeM()>✕</button></div><div class=form><div class=field><label>Name</label><input id=mname value="${esc(x.name||'')}"></div><div class=field><label>Monthly Plan</label><select id=mplan><option ${q.plan===100?'selected':''}>AED 100</option><option ${q.plan===200?'selected':''}>AED 200</option><option ${q.plan===250?'selected':''}>AED 250</option></select></div><div class=field><label>${currentBillingMonth()} Status</label><input value="${q.status}" readonly></div><div class=field><label>Paid / Due</label><input value="AED ${money(q.paid)} paid · AED ${money(q.due)} due" readonly></div><div class=field><label>Phone</label><input id=mphone value="${esc(x.phone||'')}"></div><div class=span2><button class=btn onclick="saveMember('${x.id||''}')">SAVE</button></div></div>`)};
window.memberFormById=id=>memberForm(state.data.members.find(x=>x.id===id)||{});
window.saveMember=async id=>{try{const old=state.data.members.find(x=>x.id===id)||{},plan=$('mplan').value,planAmount=planValue(plan),probe={...old,id:id||old.id,plan,planAmount},q=id?memberSummary(probe):{paid:0,due:planAmount,status:'DUE'},v={name:$('mname').value.trim(),plan,planAmount,paidAmount:q.paid,dueAmount:Math.max(0,planAmount-q.paid),status:paymentStatus(planAmount,q.paid),currentBillingMonth:currentBillingMonth(),phone:$('mphone').value.trim(),updatedAt:serverTimestamp()};if(!v.name)return toast('Enter member name');id?await updateDoc(doc(db,'members',id),v):await addDoc(collection(db,'members'),{...v,createdAt:serverTimestamp()});closeM();toast('Member saved')}catch(e){err(e)}};'''
    s = cut(s,'function members(){','function meals(){',members)

    payments = r'''function payments(){const month=currentBillingMonth(),isMember=state.profile.role==='member',self=isMember?linkedMember(auth.currentUser.uid):null,history=(isMember?state.data.payments.filter(x=>String(x.uid||'')===String(auth.currentUser.uid)):state.data.payments).filter(x=>paymentMonth(x)===month);if(isMember){const q=self?memberSummary(self,month):{plan:0,paid:0,due:0,status:'DUE'};return`<div class=note style="margin-top:12px">Billing month: <b>${month}</b></div><div class=grid>${metric('Plan','AED '+money(q.plan))}${metric('Paid','AED '+money(q.paid))}${metric('Due','AED '+money(q.due))}${metric('Status',q.status)}</div><div class=card style="margin-top:12px"><h3>Payment History</h3><div class=list>${history.length?history.map(x=>`<div class=row><span><b>${esc(x.name||self?.name||'Member')}</b><small class=muted> · ${paymentMonth(x)}</small></span><span>AED ${money(paidValue(x))}</span><span>${esc(x.status||'Recorded')}</span><span></span></div>`).join(''):'<p class=muted>No payment recorded for this month yet.</p>'}</div></div>`}const summaries=state.data.members.map(m=>({m,q:memberSummary(m,month)}));return`<div class=top style="margin-top:14px"><div><p class=muted style="margin:0">Monthly payment control · ${month}</p><div class=small>Paid / partial / due are calculated automatically.</div></div><button class=btn onclick=paymentForm()>+ Payment</button></div><div class=card style="margin-top:12px"><h3>Member Balances</h3><div class=list>${summaries.map(({m,q})=>`<div class=row><span><b>${esc(m.name)}</b><small class=muted> · Plan AED ${money(q.plan)}</small></span><span>Paid AED ${money(q.paid)}<br><small class=muted>Due AED ${money(q.due)}</small></span><span class="tag ${q.status==='DUE'?'due':q.status==='PARTIAL'?'partial':'paid'}">${q.status}</span><span><div class=actions><button class=ghost onclick="paymentFormForMember('${memberKey(m)}')">Add Payment</button><button class=ghost onclick="waDue('${esc(m.phone||'')}','${esc(m.name||'Member')}',${q.plan},${q.paid},${q.due})">WhatsApp</button></div></span></div>`).join('')}</div></div><div class=card style="margin-top:12px"><h3>${month} Payment Transactions</h3><div class=list>${history.length?history.map(x=>{const m=linkedMember(x.uid);return`<div class=row><span><b>${esc(x.name||m?.name||'Member')}</b><small class=muted> · ${paymentMonth(x)}</small></span><span>Entry AED ${money(paidValue(x))}</span><span>${esc(x.status||'Recorded')}</span><span><div class=actions><button class=ghost onclick="paymentFormById('${x.id}')">Edit</button><button class="ghost danger" onclick="deletePayment('${x.id}')">Delete</button></div></span></div>`}).join(''):'<p class=muted>No payments recorded this month.</p>'}</div></div>`}
window.paymentFormForMember=uid=>paymentForm({uid,billingMonth:currentBillingMonth()});
window.paymentForm=(x={})=>{const selected=String(x.uid||''),m=linkedMember(selected),billingMonth=String(x.billingMonth||paymentMonth(x)||currentBillingMonth()),plan=planValue(m?.planAmount||m?.plan||x.planAmount||200),current=paidValue(x),opts=state.data.members.map(mm=>'<option value="'+memberKey(mm)+'" '+(selected===memberKey(mm)?'selected':'')+'>'+esc(mm.name)+'</option>').join(''),editId=x.id||'';modal(`<div class=top><h3>${x.id?'Edit':'Add'} Payment</h3><button class=ghost onclick=closeM()>✕</button></div><div class=form><div class=field><label>Member</label><select id=puid><option value="">Select member</option>${opts}</select></div><div class=field><label>Billing Month</label><input id=pmonth type=month value="${esc(billingMonth)}"></div><div class=field><label>Name</label><input id=pname value="${esc(x.name||m?.name||'')}" readonly></div><div class=field><label>Phone</label><input id=pphone value="${esc(x.phone||m?.phone||'')}" placeholder="9715..."></div><div class=field><label>Plan Amount</label><input id=pplan type=number min=0 step=.01 value="${plan}"></div><div class=field><label>This Payment</label><input id=ppaid type=number min=.01 step=.01 value="${current||''}"></div><div class=field><label>Due After Payment</label><input id=pdue readonly></div><div class=field><label>Status After Payment</label><input id=pstatus readonly></div><div class=span2><div class=note>Each payment is a transaction. Monthly Paid = sum of all transactions for the selected member and month.</div></div><div class=span2><button class=btn id=psave>SAVE PAYMENT</button></div></div>`);$('puid').onchange=()=>syncPaymentMember(editId);$('pmonth').onchange=()=>recalcPayment(editId);$('pplan').oninput=()=>recalcPayment(editId);$('ppaid').oninput=()=>recalcPayment(editId);$('psave').onclick=()=>savePayment(editId);if(m)syncPaymentMember(editId);else recalcPayment(editId)};
window.paymentFormById=id=>paymentForm(state.data.payments.find(x=>x.id===id)||{});
window.syncPaymentMember=(editId='')=>{const m=linkedMember($('puid')?.value);if(m){$('pname').value=m.name||'';$('pphone').value=m.phone||'';$('pplan').value=planValue(m.planAmount||m.plan)}recalcPayment(editId)};
window.recalcPayment=(editId='')=>{const month=$('pmonth')?.value||currentBillingMonth(),plan=Math.max(0,Number($('pplan')?.value||0)),entry=Math.max(0,Number($('ppaid')?.value||0)),m=linkedMember($('puid')?.value),other=m?memberPaid(m,month,editId):0,total=other+entry,due=Math.max(0,plan-total),status=paymentStatus(plan,total);if($('pdue'))$('pdue').value='AED '+money(due);if($('pstatus'))$('pstatus').value=status};
window.savePayment=async id=>{try{const uid=$('puid').value,m=linkedMember(uid),billingMonth=$('pmonth').value||currentBillingMonth(),plan=Math.max(0,Number($('pplan').value||0)),entry=Math.max(0,Number($('ppaid').value||0));if(!m)return toast('Select a member');if(!billingMonth)return toast('Select billing month');if(plan<=0)return toast('Enter plan amount');if(entry<=0)return toast('Enter payment amount');const other=memberPaid(m,billingMonth,id),total=other+entry;if(total>plan+0.001)return toast('Payment exceeds remaining due');const due=Math.max(0,plan-total),status=paymentStatus(plan,total),v={uid:memberKey(m),name:m.name||'',phone:$('pphone').value.trim()||m.phone||'',billingMonth,planAmount:plan,paidAmount:entry,amount:entry,dueAmount:due,status,updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'payments',id),v);else await addDoc(collection(db,'payments'),{...v,createdAt:serverTimestamp()});if(billingMonth===currentBillingMonth())await updateDoc(doc(db,'members',m.id),{plan:'AED '+plan,planAmount:plan,paidAmount:total,dueAmount:due,status,currentBillingMonth:billingMonth,updatedAt:serverTimestamp()});closeM();toast('Payment saved · Paid AED '+money(total)+' · Due AED '+money(due)+' · '+status)}catch(e){err(e)}};
window.deletePayment=async id=>{if(!ask('Delete this payment transaction?'))return;try{await deleteDoc(doc(db,'payments',id));toast('Payment deleted · balances recalculated automatically')}catch(e){err(e)}};
window.waDue=(phone,name,plan,paid,due)=>{const status=paymentStatus(Number(plan),Number(paid)),text=encodeURIComponent(`A2 MESS HUB\nHi ${name}, payment update for ${currentBillingMonth()}:\nPlan: AED ${money(plan)}\nPaid: AED ${money(paid)}\nDue: AED ${money(due)}\nStatus: ${status}\n— Powered by TECHMANZ`);window.open(`https://wa.me/${String(phone||'').replace(/\D/g,'')}?text=${text}`,'_blank')};'''
    s = cut(s,'function payments(){','window.delRecord=',payments)

    reports = r'''function reports(){const month=currentBillingMonth(),summaries=state.data.members.map(m=>memberSummary(m,month)),paid=summaries.reduce((a,q)=>a+q.paid,0),due=summaries.reduce((a,q)=>a+q.due,0),exp=currentMonthExpenses().reduce((a,x)=>a+Number(x.amount||0),0);return`<div class=note style="margin-top:12px">Monthly report: <b>${month}</b></div><div class="grid">${metric('Income','AED '+money(paid))}${metric('Outstanding','AED '+money(due))}${metric('Expense','AED '+money(exp))}${metric('Net','AED '+money(paid-exp))}</div>`}'''
    s = cut(s,'function reports(){','function settings(){',reports)

    checks=['function currentBillingMonth()','billingMonth','Payment Transactions','Member Balances','Total Receivable','Balance Due','paymentFormForMember','PARTIAL']
    missing=[x for x in checks if x not in s]
    if missing:
        raise SystemExit(f'{app}: missing payment features: {missing}')
    app.write_text(s)
    print(f'Applied monthly payment consistency fix to {app}')


targets = [Path(x) for x in sys.argv[1:]] or [Path('/tmp/a2-pwa/www/app.html')]
for target in targets:
    if not target.exists():
        raise SystemExit(f'target not found: {target}')
    patch(target)
