from pathlib import Path

app = Path('/tmp/a2-pwa/www/app.html')
s = app.read_text()

def cut(a,b,repl):
    global s
    i=s.find(a); j=s.find(b,i)
    if i<0 or j<0: raise SystemExit(f'marker missing: {a} / {b}')
    s=s[:i]+repl.rstrip()+"\n"+s[j:]

helpers = r'''function planValue(v){const n=Number(String(v??'').replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:0}
function paidValue(x){const n=Number(x?.paidAmount??x?.amount??0);return Number.isFinite(n)?n:0}
function memberKey(m){return String(m?.uid||m?.id||'')}
function linkedMember(uid){return state.data.members.find(m=>memberKey(m)===String(uid||''))}
function memberPaid(m,excludeId=''){const k=memberKey(m);return state.data.payments.reduce((sum,p)=>sum+((p.id!==excludeId&&String(p.uid||'')===k)?paidValue(p):0),0)}
function paymentStatus(plan,paid){const due=Math.max(0,plan-paid);return paid<=0?'DUE':due>0?'PARTIAL':'PAID'}
function memberSummary(m){const plan=planValue(m?.planAmount||m?.plan),paid=memberPaid(m),due=Math.max(0,plan-paid);return{plan,paid,due,status:paymentStatus(plan,paid)}}
function money(n){return Number(n||0).toFixed(2)}
'''
if 'function planValue(v)' not in s:
    s=s.replace('function dashboard(){',helpers+'\nfunction dashboard(){',1)
if '.tag.partial{' not in s:
    s=s.replace('</style>','.tag.partial{background:#f6cb67;color:#201600}\n</style>',1)

cut('function dashboard(){','function users(){',r'''function dashboard(){const paid=state.data.payments.reduce((a,x)=>a+paidValue(x),0),due=state.data.members.reduce((a,m)=>a+memberSummary(m).due,0),exp=state.data.expenses.reduce((a,x)=>a+Number(x.amount||0),0);return`<div class=grid>${metric('Members',state.data.members.length)}${metric('Collected','AED '+paid.toFixed(0))}${metric('Due','AED '+due.toFixed(0))}${metric('Expenses','AED '+exp.toFixed(0))}${metric('Balance','AED '+(paid-exp).toFixed(0))}</div>`}''')

cut('function members(){','function meals(){',r'''function members(){return`<div class=top style="margin-top:14px"><p class=muted>Subscription members · automatic payment balance</p>${state.profile.role==='admin'?'<button class=btn onclick=memberForm()>+ Member Record</button>':''}</div><div class="card list">${state.data.members.map(x=>{const q=memberSummary(x);return`<div class=row><span><b>${esc(x.name)}</b><small class=muted> · Plan AED ${money(q.plan)}</small></span><span>Paid AED ${money(q.paid)}<br><small class=muted>Due AED ${money(q.due)}</small></span><span class="tag ${q.status==='DUE'?'due':q.status==='PARTIAL'?'partial':''}">${q.status}</span><span>${state.profile.role==='admin'?`<div class=actions><button class=ghost onclick="memberFormById('${x.id}')">Edit</button><button class="ghost danger" onclick="delRecord('members','${x.id}','member')">Delete</button></div>`:''}</span></div>`}).join('')}</div>`}
window.memberForm=(x={})=>{const q=x.id?memberSummary(x):{plan:planValue(x.plan||'AED 200'),paid:0,due:planValue(x.plan||'AED 200'),status:'DUE'};modal(`<div class=top><h3>Member</h3><button class=ghost onclick=closeM()>✕</button></div><div class=form><div class=field><label>Name</label><input id=mname value="${esc(x.name||'')}"></div><div class=field><label>Plan</label><select id=mplan><option ${q.plan===100?'selected':''}>AED 100</option><option ${q.plan===200?'selected':''}>AED 200</option><option ${q.plan===250?'selected':''}>AED 250</option></select></div><div class=field><label>Status</label><input value="${q.status}" readonly></div><div class=field><label>Paid / Due</label><input value="AED ${money(q.paid)} paid · AED ${money(q.due)} due" readonly></div><div class=field><label>Phone</label><input id=mphone value="${esc(x.phone||'')}"></div><div class=span2><button class=btn onclick="saveMember('${x.id||''}')">SAVE</button></div></div>`)};
window.memberFormById=id=>memberForm(state.data.members.find(x=>x.id===id)||{});
window.saveMember=async id=>{try{const old=state.data.members.find(x=>x.id===id)||{},plan=$('mplan').value,planAmount=planValue(plan),probe={...old,id:id||old.id,plan,planAmount},paid=id?memberPaid(probe):0,due=Math.max(0,planAmount-paid),status=paymentStatus(planAmount,paid),v={name:$('mname').value.trim(),plan,planAmount,paidAmount:paid,dueAmount:due,status,phone:$('mphone').value.trim(),updatedAt:serverTimestamp()};if(!v.name)return toast('Enter member name');id?await updateDoc(doc(db,'members',id),v):await addDoc(collection(db,'members'),{...v,createdAt:serverTimestamp()});closeM();toast('Member saved · '+status)}catch(e){err(e)}};''')

cut('function payments(){','window.delRecord=',r'''function payments(){const rows=state.profile.role==='member'?state.data.payments.filter(x=>x.uid===auth.currentUser.uid):state.data.payments;return`<div class=top style="margin-top:14px"><p class=muted>Plan / paid / due calculate automatically</p>${state.profile.role==='admin'?'<button class=btn onclick=paymentForm()>+ Payment</button>':''}</div><div class="card list">${rows.map(x=>{const m=linkedMember(x.uid),plan=planValue(m?.planAmount||m?.plan||x.planAmount||x.plan),paid=m?memberPaid(m):paidValue(x),due=Math.max(0,plan-paid),status=paymentStatus(plan,paid);return`<div class=row><span><b>${esc(x.name||m?.name||'Member')}</b><small class=muted> · Plan AED ${money(plan)}</small></span><span>Paid AED ${money(paid)}<br><small class=muted>Due AED ${money(due)}</small></span><span class="tag ${status==='DUE'?'due':status==='PARTIAL'?'partial':''}">${status}</span><span>${state.profile.role==='admin'?`<div class=actions><button class=ghost onclick="paymentFormById('${x.id}')">Edit</button><button class=ghost onclick="waDue('${esc(x.phone||m?.phone||'')}','${esc(x.name||m?.name||'Member')}',${plan},${paid},${due})">WhatsApp</button><button class="ghost danger" onclick="delRecord('payments','${x.id}','payment')">Delete</button></div>`:''}</span></div>`}).join('')}</div>`}
window.paymentForm=(x={})=>{const m=linkedMember(x.uid),plan=planValue(m?.planAmount||m?.plan||x.planAmount||200),current=paidValue(x),opts=state.data.members.map(mm=>'<option value="'+memberKey(mm)+'" '+(x.uid===memberKey(mm)?'selected':'')+'>'+esc(mm.name)+'</option>').join(''),editId=x.id||'';modal(`<div class=top><h3>${x.id?'Edit':'Add'} Payment</h3><button class=ghost onclick=closeM()>✕</button></div><div class=form><div class=field><label>Member</label><select id=puid><option value="">Manual / Not linked</option>${opts}</select></div><div class=field><label>Name</label><input id=pname value="${esc(x.name||m?.name||'')}"></div><div class=field><label>Phone</label><input id=pphone value="${esc(x.phone||m?.phone||'')}" placeholder="9715..."></div><div class=field><label>Plan Amount</label><input id=pplan type=number min=0 step=.01 value="${plan}"></div><div class=field><label>Paid Amount</label><input id=ppaid type=number min=0 step=.01 value="${current}"></div><div class=field><label>Due Amount</label><input id=pdue readonly></div><div class=field><label>Status</label><input id=pstatus readonly></div><div class=span2><div class=note>Example: AED 200 plan − AED 80 paid = AED 120 due · PARTIAL</div></div><div class=span2><button class=btn id=psave>SAVE</button></div></div>`);$('puid').onchange=()=>syncPaymentMember(editId);$('pplan').oninput=()=>recalcPayment(editId);$('ppaid').oninput=()=>recalcPayment(editId);$('psave').onclick=()=>savePayment(editId);recalcPayment(editId)};
window.paymentFormById=id=>paymentForm(state.data.payments.find(x=>x.id===id)||{});
window.syncPaymentMember=(editId='')=>{const m=linkedMember($('puid')?.value);if(m){$('pname').value=m.name||'';$('pphone').value=m.phone||'';$('pplan').value=planValue(m.planAmount||m.plan)}recalcPayment(editId)};
window.recalcPayment=(editId='')=>{const plan=Math.max(0,Number($('pplan')?.value||0)),entry=Math.max(0,Number($('ppaid')?.value||0)),m=linkedMember($('puid')?.value),other=m?memberPaid(m,editId):0,total=other+entry,due=Math.max(0,plan-total),status=paymentStatus(plan,total);if($('pdue'))$('pdue').value='AED '+money(due);if($('pstatus'))$('pstatus').value=status};
window.savePayment=async id=>{try{const uid=$('puid').value,m=linkedMember(uid),plan=Math.max(0,Number($('pplan').value||0)),entry=Math.max(0,Number($('ppaid').value||0));if(plan<=0)return toast('Enter plan amount');const other=m?memberPaid(m,id):0,total=other+entry;if(total>plan)return toast('Paid amount cannot exceed plan amount');const due=Math.max(0,plan-total),status=paymentStatus(plan,total),v={uid,name:$('pname').value.trim()||m?.name||'',phone:$('pphone').value.trim()||m?.phone||'',planAmount:plan,paidAmount:entry,amount:entry,dueAmount:due,status,updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'payments',id),v);else await addDoc(collection(db,'payments'),{...v,createdAt:serverTimestamp()});if(m)await updateDoc(doc(db,'members',m.id),{plan:'AED '+plan,planAmount:plan,paidAmount:total,dueAmount:due,status,updatedAt:serverTimestamp()});closeM();toast('Payment saved · Paid AED '+money(total)+' · Due AED '+money(due))}catch(e){err(e)}};
window.waDue=(phone,name,plan,paid,due)=>{const status=paymentStatus(Number(plan),Number(paid)),text=encodeURIComponent(`A2 MESS HUB\nHi ${name}, payment update:\nPlan: AED ${money(plan)}\nPaid: AED ${money(paid)}\nDue: AED ${money(due)}\nStatus: ${status}\n— Powered by TECHMANZ`);window.open(`https://wa.me/${String(phone||'').replace(/\D/g,'')}?text=${text}`,'_blank')};''')

cut('function reports(){','function settings(){',r'''function reports(){const paid=state.data.payments.reduce((a,x)=>a+paidValue(x),0),due=state.data.members.reduce((a,m)=>a+memberSummary(m).due,0),exp=state.data.expenses.reduce((a,x)=>a+Number(x.amount||0),0);return`<div class="grid">${metric('Income','AED '+paid.toFixed(2))}${metric('Outstanding','AED '+due.toFixed(2))}${metric('Expense','AED '+exp.toFixed(2))}${metric('Net','AED '+(paid-exp).toFixed(2))}</div>`}''')

app.write_text(s)
print('Applied safe AED 100 + partial payment calculations')
