from pathlib import Path
import sys

paths=[Path(p) for p in sys.argv[1:]] or [Path('/tmp/a2-pwa/www/app.html')]
if not paths[0].exists() and not sys.argv[1:]: paths=[Path('www/app.html')]

CSS=r'''<style id="a2-reference-actions">
.ref-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0}.ref-search{flex:1 1 210px}.ref-chips{display:flex;gap:7px;flex-wrap:wrap}.ref-chip{padding:8px 11px;border-radius:999px;border:1px solid #27b97955;background:#071d16;color:#bcd2c8;font:inherit;font-size:11px;font-weight:750}.ref-chip.on{background:#20dc89;color:#022116}.ref-month{display:grid;grid-template-columns:40px 1fr 40px;gap:8px;align-items:center;margin:12px 0}.ref-month b{text-align:center}.ref-progress{height:9px;background:#ffffff12;border-radius:99px;overflow:hidden;margin-top:10px}.ref-progress i{display:block;height:100%;background:#20dc89;border-radius:99px}.ref-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:13px}.ref-action{text-align:left;min-height:92px;cursor:pointer}.settings-item[data-action]{cursor:pointer}@media(max-width:620px){.ref-actions{grid-template-columns:1fr}.ref-search{flex-basis:100%}}
</style>'''

MEMBERS=r'''function members(){const month=currentBillingMonth(),v=window._memberView||{},term=String(v.q||'').toLowerCase(),status=v.status||'ALL',all=state.data.members.map(m=>({m,q:memberSummary(m,month)})),rows=all.filter(x=>(status==='ALL'||x.q.status===status)&&(!term||[x.m.name,x.m.phone,x.m.plan].some(y=>String(y||'').toLowerCase().includes(term))));const count=k=>all.filter(x=>x.q.status===k).length;return`<div class=top style="margin-top:14px"><div><p class=muted style="margin:0">${all.length} Members</p><div class=small>Search and live payment status</div></div>${state.profile.role==='admin'?'<button class=btn onclick=memberForm()>+ Add</button>':''}</div><div class=ref-toolbar><input class=ref-search placeholder="Search members…" value="${esc(v.q||'')}" oninput="setMemberView('q',this.value)"><div class=ref-chips>${[['ALL',all.length],['PAID',count('PAID')],['DUE',count('DUE')],['PARTIAL',count('PARTIAL')]].map(x=>`<button class="ref-chip ${status===x[0]?'on':''}" onclick="setMemberView('status','${x[0]}')">${x[0][0]+x[0].slice(1).toLowerCase()} (${x[1]})</button>`).join('')}</div></div><div class="card list">${rows.map(({m,q})=>`<div class=row><span><b>${esc(m.name)}</b><small class=muted> · Plan AED ${money(q.plan)}</small></span><span>Paid AED ${money(q.paid)}<br><small class=muted>Due AED ${money(q.due)}</small></span><span class="tag ${q.status==='DUE'?'due':q.status==='PARTIAL'?'partial':'paid'}">${q.status}</span><span>${state.profile.role==='admin'?`<div class=actions><button class=ghost onclick="paymentFormForMember('${memberKey(m)}')">Payment</button><button class=ghost onclick="memberFormById('${m.id}')">Edit</button><button class="ghost danger" onclick="delRecord('members','${m.id}','member')">Delete</button></div>`:''}</span></div>`).join('')||'<p class=muted>No members match this filter.</p>'}</div>`}'''

INVENTORY=r'''function inventory(){const v=window._inventoryView||{},term=String(v.q||'').toLowerCase(),filter=v.filter||'ALL',all=state.data.inventory,low=all.filter(x=>Number(x.qty||0)<=Number(x.min||0)).length,rows=all.filter(x=>{const l=Number(x.qty||0)<=Number(x.min||0);return(filter==='ALL'||filter==='LOW'&&l||filter==='OK'&&!l)&&(!term||[x.name,x.unit].some(y=>String(y||'').toLowerCase().includes(term)))});return`<div class=top style="margin-top:14px"><div><p class=muted style="margin:0">${all.length} Stock Items</p><div class=small>${low} low stock</div></div>${state.profile.role!=='member'?'<button class=btn onclick=invForm()>+ Add</button>':''}</div><div class=ref-toolbar><input class=ref-search placeholder="Search items…" value="${esc(v.q||'')}" oninput="setInventoryView('q',this.value)"><div class=ref-chips>${[['ALL','All'],['LOW','Low Stock ('+low+')'],['OK','In Stock']].map(x=>`<button class="ref-chip ${filter===x[0]?'on':''}" onclick="setInventoryView('filter','${x[0]}')">${x[1]}</button>`).join('')}</div></div><div class="card list">${rows.map(x=>{const l=Number(x.qty||0)<=Number(x.min||0);return`<div class=row><span><b>${esc(x.name)}</b></span><span>${Number(x.qty||0)} ${esc(x.unit||'')}</span><span class="tag ${l?'due':''}">${l?'LOW STOCK':'IN STOCK'}</span><span>${state.profile.role==='admin'?`<div class=actions><button class=ghost onclick="invFormById('${x.id}')">Edit</button><button class="ghost danger" onclick="delRecord('inventory','${x.id}','stock item')">Delete</button></div>`:''}</span></div>`}).join('')||'<p class=muted>No items match this filter.</p>'}</div>`}'''

REPORTS=r'''function reports(){const month=window._reportMonth||currentBillingMonth(),s=state.data.members.map(m=>({m,q:memberSummary(m,month)})),paid=s.reduce((a,x)=>a+x.q.paid,0),due=s.reduce((a,x)=>a+x.q.due,0),total=s.reduce((a,x)=>a+x.q.plan,0),ex=state.data.expenses.filter(x=>expenseMonth(x)===month),spent=ex.reduce((a,x)=>a+Number(x.amount||0),0),pct=total?Math.min(100,paid/total*100):0;return`<div class=ref-month><button class=ghost onclick="moveReportMonth(-1)">‹</button><b>${month}</b><button class=ghost onclick="moveReportMonth(1)">›</button></div><div class=grid>${metric('Income','AED '+money(paid))}${metric('Expenses','AED '+money(spent))}${metric('Balance','AED '+money(paid-spent))}${metric('Outstanding','AED '+money(due))}</div><div class=card style="margin-top:12px"><div class=top><div><h3 style="margin:0">Collection Progress</h3><div class=small>AED ${money(paid)} of AED ${money(total)}</div></div><b>${pct.toFixed(0)}%</b></div><div class=ref-progress><i style="width:${pct}%"></i></div></div><div class=ref-actions><button class="card ref-action" onclick="exportMemberReport()"><b>👥 Member Report</b><small class=muted>Payment status and dues</small></button><button class="card ref-action" onclick="exportExpenseReport()"><b>🧾 Expense Report</b><small class=muted>Detailed expense breakdown</small></button><button class="card ref-action" onclick="exportFullReport()"><b>📥 Export Report</b><small class=muted>Complete CSV download</small></button></div>`}'''

HELPERS=r'''
window.setMemberView=(k,v)=>{window._memberView={...(window._memberView||{}),[k]:v};render()};window.setInventoryView=(k,v)=>{window._inventoryView={...(window._inventoryView||{}),[k]:v};render()};
function expenseMonth(x){const d=x?.createdAt?.toDate?.()||x?.updatedAt?.toDate?.();return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:''}
window.moveReportMonth=n=>{const d=new Date((window._reportMonth||currentBillingMonth())+'-01T00:00:00');d.setMonth(d.getMonth()+n);window._reportMonth=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;render()};
function csv(v){return '"'+String(v??'').replaceAll('"','""')+'"'}function downloadCsv(name,rows){const b=new Blob([rows.map(r=>r.map(csv).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.exportMemberReport=()=>{const m=window._reportMonth||currentBillingMonth();downloadCsv(`A2-Members-${m}.csv`,[['Member','Plan AED','Paid AED','Due AED','Status'],...state.data.members.map(x=>{const q=memberSummary(x,m);return[x.name,q.plan,q.paid,q.due,q.status]})])};window.exportExpenseReport=()=>{const m=window._reportMonth||currentBillingMonth();downloadCsv(`A2-Expenses-${m}.csv`,[['Expense','Category','Amount AED'],...state.data.expenses.filter(x=>expenseMonth(x)===m).map(x=>[x.title,x.category||'General',x.amount||0])])};window.exportFullReport=()=>{exportMemberReport();setTimeout(exportExpenseReport,250)};
'''

def replace(s,name,new,next_marker):
    a=s.find('function '+name+'('); b=s.find(next_marker,a)
    if a<0 or b<0: raise SystemExit(name+' markers missing')
    return s[:a]+new+s[b:]

for app in paths:
    s=app.read_text()
    if 'id="a2-reference-actions"' not in s:s=s.replace('</head>',CSS+'\n</head>',1)
    s=replace(s,'members',MEMBERS,'\nwindow.memberForm=')
    s=replace(s,'inventory',INVENTORY,'\nwindow.invForm=')
    s=replace(s,'reports',REPORTS,'\nfunction settings(){')
    marker='\nconst callCreateManagedUser='
    if 'window.setMemberView=' not in s:s=s.replace(marker,HELPERS+marker,1)
    required=['a2-reference-actions','setMemberView','setInventoryView','exportMemberReport','exportExpenseReport','Collection Progress']
    missing=[x for x in required if x not in s]
    if missing:raise SystemExit('Reference actions missing: '+', '.join(missing))
    app.write_text(s)
    print('Applied functional reference UI actions to',app)
