from pathlib import Path
import re, sys

# FINAL APPROVED BRANDING ONLY.
# Do not draw/re-create the TM logo here. Use the exact approved logo asset.
if sys.argv[1:]:
    paths=[Path(p) for p in sys.argv[1:]]
    root=paths[0].parent
else:
    root=Path('/tmp/a2-pwa/www')
    if not root.exists():
        root=Path('www')
    paths=[root/'app.html', root/'index.html']

ASSET='./tm-solutions-approved.webp'
LOGO=f'''<span class="tm-approved-logo-wrap"><img class="tm-approved-logo" src="{ASSET}" alt="TM Solutions"></span>'''
BRAND=f'''<div class="powered tm-powered"><span class="tm-powered-label">Powered by</span>{LOGO}</div>'''
SPLASH_BRAND=f'''<div class="tech tm-powered"><span class="tm-powered-label">Powered by</span>{LOGO}</div>'''

for page in paths:
    if not page.exists():
        raise SystemExit(f'Branding target not found: {page}')
    s=page.read_text()

    # Remove any previously generated/re-created TM artwork. The approved image is the only logo allowed.
    s=re.sub(r'<svg\b[^>]*class=["\'][^"\']*tm-logo-svg[^"\']*["\'][^>]*>.*?</svg>', '', s, flags=re.I|re.S)
    s=re.sub(r'<img\b[^>]*src=["\'][^"\']*tm-solutions-logo\.(?:png|webp)[^"\']*["\'][^>]*>', '', s, flags=re.I)

    if page.name == 'app.html':
        # Replace all previously injected powered-by blocks.
        s=re.sub(r'<div\b[^>]*class=["\'][^"\']*tm-powered[^"\']*["\'][^>]*>.*?</div>', BRAND, s, flags=re.I|re.S)
        # Replace original/legacy powered-by elements generated by older UI patches.
        s=re.sub(r'<p\b[^>]*class=["\'][^"\']*powered[^"\']*["\'][^>]*>.*?</p>', BRAND, s, flags=re.I|re.S)
        s=re.sub(r'<div\b[^>]*class=["\'][^"\']*powered[^"\']*["\'][^>]*>.*?</div>', BRAND, s, flags=re.I|re.S)
        s=s.replace('Powered by TECHMANZ','Powered by TM Solutions')
        s=s.replace('POWERED BY TECHMANZ','POWERED BY TM SOLUTIONS')
        s=s.replace('Powered by TECH MANZ','Powered by TM Solutions')
        s=s.replace('POWERED BY TECH MANZ','POWERED BY TM SOLUTIONS')
        s=s.replace('⚡ TECHMANZ','TM Solutions')
        s=s.replace('⚡ TECH MANZ','TM Solutions')
    else:
        # Splash screen before app.html loads.
        s=re.sub(r'<div\b[^>]*class=["\']tech(?:\s+tm-powered)?["\'][^>]*>.*?</div>', SPLASH_BRAND, s, count=1, flags=re.I|re.S)
        if 'tm-approved-logo' not in s:
            s=s.replace('</body>', SPLASH_BRAND+'</body>', 1)
        s=s.replace('Powered by TECHMANZ','Powered by TM Solutions')
        s=s.replace('POWERED BY TECHMANZ','POWERED BY TM SOLUTIONS')
        s=s.replace('Powered by TECH MANZ','Powered by TM Solutions')
        s=s.replace('POWERED BY TECH MANZ','POWERED BY TM SOLUTIONS')

    page.write_text(s)
    print('Applied exact approved TM Solutions logo to', page)

# Remove all old branding assets from the generated site. Keep only the approved file.
for old in ('techmanz-logo.jpg','tm-solutions-logo.png','tm-solutions-logo.webp','tm-solutions-approved.svg'):
    p=root/old
    if p.exists():
        p.unlink()
        print('Removed non-approved branding asset', p)

approved=root/'tm-solutions-approved.webp'
if not approved.exists() or approved.stat().st_size < 4000:
    raise SystemExit('Approved TM Solutions logo asset missing or invalid')

# Professional effects around the approved logo only; the artwork itself is not changed.
css=root/'mobile-fixes.css'
if css.exists():
    c=css.read_text()
    c=re.sub(r"background-image\s*:\s*url\([^)]*(?:techmanz-logo|tm-solutions-logo)[^)]*\)\s*;?",'background-image:none!important;',c,flags=re.I)
    c += '''\n/* Approved TM Solutions branding — exact logo, effects only */\n.tm-powered,.powered.tm-powered{display:grid!important;justify-items:center!important;align-items:center!important;place-items:center!important;justify-self:center!important;align-self:center!important;gap:5px!important;width:min(210px,calc(100% - 24px))!important;max-width:210px!important;height:auto!important;min-height:0!important;margin:18px auto 8px!important;margin-left:auto!important;margin-right:auto!important;padding:0!important;overflow:visible!important;border:0!important;border-radius:0!important;background:none!important;background-image:none!important;box-shadow:none!important;color:#839f95!important;text-align:center!important;float:none!important}\n.tm-powered-label{display:block!important;width:100%!important;text-align:center!important;color:#8aa69c!important;font-size:9px!important;line-height:1.2!important;font-weight:800!important;letter-spacing:.14em!important;text-transform:uppercase!important}\n.tm-approved-logo-wrap{position:relative!important;display:grid!important;place-items:center!important;width:154px!important;max-width:min(62vw,100%)!important;margin:0 auto!important;left:auto!important;right:auto!important;isolation:isolate!important}\n.tm-approved-logo-wrap::before{content:''!important;position:absolute!important;inset:20% 10%!important;border-radius:50%!important;background:radial-gradient(circle,rgba(35,155,255,.32),rgba(0,111,255,.12) 42%,transparent 72%)!important;filter:blur(14px)!important;opacity:.65!important;z-index:-1!important;animation:tmAura 3.2s ease-in-out infinite!important}\n.tm-approved-logo{display:block!important;width:100%!important;height:auto!important;object-fit:contain!important;object-position:center center!important;margin:0 auto!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;filter:drop-shadow(0 0 8px rgba(31,161,255,.36)) drop-shadow(0 8px 16px rgba(0,0,0,.28))!important;animation:tmFloat 4.2s ease-in-out infinite,tmGlow 3.2s ease-in-out infinite!important}\n.tech.tm-powered{left:50%!important;right:auto!important;transform:translateX(-50%)!important;width:min(210px,calc(100vw - 24px))!important;max-width:calc(100vw - 24px)!important;margin-left:0!important;margin-right:0!important}\n.settings-brand .tm-powered{margin-top:14px!important;max-width:220px!important}.settings-brand .tm-approved-logo-wrap{width:162px!important}.side .tm-powered{margin-top:22px!important;width:100%!important;max-width:210px!important}.side .tm-approved-logo-wrap{width:126px!important}\n@keyframes tmFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}\n@keyframes tmGlow{0%,100%{filter:drop-shadow(0 0 7px rgba(31,161,255,.30)) drop-shadow(0 8px 16px rgba(0,0,0,.28))}50%{filter:drop-shadow(0 0 15px rgba(34,174,255,.62)) drop-shadow(0 8px 18px rgba(0,0,0,.34))}}\n@keyframes tmAura{0%,100%{opacity:.42;transform:scale(.94)}50%{opacity:.82;transform:scale(1.08)}}\n@media(max-width:560px){.tm-powered,.powered.tm-powered{width:min(190px,calc(100% - 20px))!important}.tech.tm-powered{width:min(190px,calc(100vw - 20px))!important}.tm-approved-logo-wrap{width:148px!important}.settings-brand .tm-approved-logo-wrap{width:156px!important}}\n@media(prefers-reduced-motion:reduce){.tm-approved-logo,.tm-approved-logo-wrap::before{animation:none!important}}\n'''
    css.write_text(c)

# PWA metadata and offline cache.
manifest=root/'manifest.webmanifest'
if manifest.exists():
    m=manifest.read_text().replace('Powered by TECHMANZ','Powered by TM Solutions').replace('Powered by TECH MANZ','Powered by TM Solutions')
    manifest.write_text(m)

sw=root/'sw.js'
if sw.exists():
    w=sw.read_text()
    if './tm-solutions-approved.webp' not in w:
        w=w.replace("'./logo.svg']", "'./logo.svg','./tm-solutions-approved.webp']")
    sw.write_text(w)

# Hard stop if any old/re-created branding survives the generated live build.
scan='\n'.join(p.read_text(errors='ignore') for p in (root/'app.html',root/'index.html',root/'mobile-fixes.css',root/'manifest.webmanifest') if p.exists())
if re.search(r'TECH\s*MANZ|techmanz-logo|tm-solutions-logo\.(?:png|webp)|tm-logo-svg', scan, re.I):
    raise SystemExit('Old or re-created TM branding still exists in generated live files')
if scan.count('tm-solutions-approved.webp') < 2 or 'tm-approved-logo' not in scan:
    raise SystemExit('Approved TM Solutions branding missing from generated live files')
