from pathlib import Path

app = Path('/tmp/a2-pwa/www/app.html')
if not app.exists():
    app = Path('www/app.html')
s = app.read_text()

start = s.find('function users(){')
end = s.find('function members(){', start)
if start < 0 or end < 0:
    raise SystemExit('users/members markers not found')

replacement = r'''function linkedMemberForUser(u){if(!u)return null;return state.data.members.find(m=>String(m.id||'')===String(u.memberId||'')||String(m.uid||'')===String(u.uid||u.id||''))||null}
function users(){return`<div class=top style="margin-top:14px"><p class=muted>Admin creates Member/Chef accounts and links Member logins to existing member records.</p><button class=btn onclick=userForm()>+ Create User</button></div><div class="card list">${state.data.users.map(u=>{const lm=linkedMemberForUser(u);return`<div class=row><span><b>${esc(u.name)}</b><small class=muted> · ${esc(u.email)}</small>${lm?`<small class=muted> · Linked: ${esc(lm.name)}</small>`:''}</span><span>${esc(u.role)}</span><span>${u.active===false?'Disabled':'Active'}</span><span>${u.role!=='admin'?`<div class=actions><button class=ghost onclick="editUser('${u.id}')">Edit</button><button class=ghost onclick="toggleUser('${u.id}',${u.active===false})">${u.active===false?'Enable':'Disable'}</button><button class="ghost danger" onclick="removeUserProfile('${u.id}')">Remove</button></div>`:''}</span></div>`}).join('')}</div><div class=note style="margin-top:12px">For Member users, choose an existing Member record. Name, plan, phone and member balance data stay connected to that member record.</div>`}
window.userForm=(u={})=>{const linked=linkedMemberForUser(u),selected=String(linked?.id||u.memberId||''),opts=state.data.members.map(m=>`<option value="${esc(m.id)}" ${selected===String(m.id)?'selected':''}>${esc(m.name)} · ${esc(m.plan||'No plan')} · ${esc(m.phone||'No phone')}</option>`).join('');modal(`<div class=top><h3>${u.id?'Edit':'Create'} User</h3><button class=ghost onclick=closeM()>✕</button></div><div class=form><div class=field><label>Role</label><select id=urole><option value=member ${u.role!=='chef'?'selected':''}>Member</option><option value=chef ${u.role==='chef'?'selected':''}>Chef</option></select></div><div class=field><label>Link with Member</label><select id=umember><option value="">Select Member</option>${opts}</select></div><div class=field><label>Name</label><input id=uname value="${esc(linked?.name||u.name||'')}"></div>${u.id?`<div class=field><label>Email</label><input value="${esc(u.email||'')}" readonly></div>`:`<div class=field><label>Email</label><input id=uemail type=email value="${esc(linked?.email||'')}"></div><div class="field span2"><label>Temporary Password (6+)</label><input id=upass type=password></div>`}<div class="span2 note" id=memberInfo>${linked?`Linked member: <b>${esc(linked.name)}</b> · Plan ${esc(linked.plan||'-')} · Phone ${esc(linked.phone||'-')}`:'Choose a Member to automatically use that member data.'}</div><div class=span2><button class=btn onclick="saveUser('${u.id||''}')">SAVE</button></div></div>`);$('umember').onchange=syncUserMember;$('urole').onchange=syncUserRole;syncUserRole()};
window.syncUserRole=()=>{const isMember=$('urole')?.value==='member';if($('umember'))$('umember').disabled=!isMember;if(!isMember&&$('memberInfo'))$('memberInfo').innerHTML='Chef account does not need a member link.';if(isMember)syncUserMember()};
window.syncUserMember=()=>{if(!$('umember')||$('urole')?.value!=='member')return;const m=state.data.members.find(x=>String(x.id)===String($('umember').value));if(!m){if($('memberInfo'))$('memberInfo').innerHTML='Choose a Member to automatically use that member data.';return}if($('uname'))$('uname').value=m.name||'';if($('uemail')&&!$('uemail').value)$('uemail').value=m.email||'';if($('memberInfo'))$('memberInfo').innerHTML=`Linked member: <b>${esc(m.name)}</b> · Plan ${esc(m.plan||'-')} · Phone ${esc(m.phone||'-')}`};
window.editUser=id=>userForm(state.data.users.find(x=>x.id===id)||{});
window.saveUser=async id=>{try{const role=$('urole').value,memberId=role==='member'?$('umember').value:'',member=memberId?state.data.members.find(x=>String(x.id)===String(memberId)):null;if(role==='member'&&!member)return toast('Select a member to link');const name=(member?.name||$('uname').value).trim();if(!name)return toast('Enter name');if(id){const old=state.data.users.find(x=>x.id===id)||{},oldMember=linkedMemberForUser(old),b=writeBatch(db);b.update(doc(db,'users',id),{name,role,memberId:member?.id||'',updatedAt:serverTimestamp()});if(oldMember&&(!member||oldMember.id!==member.id))b.update(doc(db,'members',oldMember.id),{uid:'',updatedAt:serverTimestamp()});if(member)b.update(doc(db,'members',member.id),{uid:id,email:old.email||member.email||'',updatedAt:serverTimestamp()});await b.commit();closeM();return toast('User updated and member linked')}const email=$('uemail').value.trim().toLowerCase(),password=$('upass').value;if(!email||password.length<6)return toast('Enter valid email/password');if(member?.uid&&String(member.uid)!==String(member.id))return toast('This member is already linked to another login');const c=await createUserWithEmailAndPassword(creatorAuth,email,password);await signOut(creatorAuth);const b=writeBatch(db);b.set(doc(db,'users',c.user.uid),{uid:c.user.uid,name,email,role,memberId:member?.id||'',active:true,createdBy:auth.currentUser.uid,createdAt:serverTimestamp()});if(member)b.update(doc(db,'members',member.id),{uid:c.user.uid,email,updatedAt:serverTimestamp()});await b.commit();closeM();toast('User created and member linked')}catch(e){try{await signOut(creatorAuth)}catch{}err(e)}};
window.toggleUser=async(id,isDisabled)=>{try{await updateDoc(doc(db,'users',id),{active:isDisabled,updatedAt:serverTimestamp()});const u=state.data.users.find(x=>x.id===id),m=linkedMemberForUser(u);if(m)await updateDoc(doc(db,'members',m.id),{active:isDisabled,updatedAt:serverTimestamp()});toast(isDisabled?'User enabled':'User disabled')}catch(e){err(e)}};
window.removeUserProfile=async id=>{if(!ask('Remove this user profile? The Firebase Auth login will remain, but app access will stop.'))return;try{const u=state.data.users.find(x=>x.id===id),m=linkedMemberForUser(u),b=writeBatch(db);b.delete(doc(db,'users',id));if(m)b.update(doc(db,'members',m.id),{uid:'',updatedAt:serverTimestamp()});await b.commit();toast('User profile removed; member record kept')}catch(e){err(e)}};
window.resetUser=async email=>{try{await sendPasswordResetEmail(auth,email);toast('Password reset email sent')}catch(e){err(e)}};
'''

s = s[:start] + replacement + s[end:]

required = ['function linkedMemberForUser(u)', 'Link with Member', 'memberId:', 'User created and member linked', 'member record kept']
missing = [x for x in required if x not in s]
if missing:
    raise SystemExit('User/member link patch missing: ' + ', '.join(missing))

app.write_text(s)
print('Added user-to-member linking')
