const BUILD='3fa4a9c3ce5603f06ad28a8cac083c75694a231d';const CACHE=`a2-mess-hub-${BUILD}`;const CORE=['./','./index.html','./app.html','./mobile-fixes.css','./manifest.webmanifest','./pwa.js','./logo.svg','./tm-solutions-approved.webp'];self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('a2-mess-hub-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==location.origin)return;e.respondWith(fetch(e.request).then(r=>{if(r&&r.ok){const x=r.clone();caches.open(CACHE).then(c=>c.put(e.request,x))}return r}).catch(()=>caches.match(e.request).then(x=>x||caches.match('./index.html'))))});

// firebase-messaging-sw: A2 MESS HUB background mobile notifications
importScripts('https://www.gstatic.com/firebasejs/11.9.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/11.9.1/firebase-messaging-compat.js');
firebase.initializeApp({apiKey:'AIzaSyDOUJGSLfDrmmc74YUGRkDU1b4P2gYmGyU',authDomain:'a2-mess-hub.firebaseapp.com',projectId:'a2-mess-hub',storageBucket:'a2-mess-hub.firebasestorage.app',messagingSenderId:'451214844236',appId:'1:451214844236:android:546b7783ecf04e40af6fe9'});
const a2Messaging=firebase.messaging();
a2Messaging.onBackgroundMessage(payload=>{const n=payload.notification||{},d=payload.data||{};return self.registration.showNotification(n.title||d.title||'A2 MESS HUB',{body:n.body||d.body||'New update',icon:'./logo.svg',badge:'./logo.svg',data:{url:d.url||'./'},tag:d.tag||'a2-mess-hub'})});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){if('focus'in w)return w.focus()}return clients.openWindow(event.notification.data?.url||'./')}))});
